### ISSUE TITLE
error TS2304: Cannot find name 'Response'.

### ISSUE THREAD

**Issue by ronenlh** [bschlenk/node-roku-client#143] opened 2019-12-10 08:14 UTC
node_modules/roku-client/dist/client.d.ts:29:15 - error TS2304: Cannot find name 'Response'.

29     response: Response;
                 ~~~~~~~~

**Comment by bschlenk** [comment] 2020-01-09 01:48
`Response` comes from typescript's `lib.dom.d.ts` file. What version of typescript are you using?

**Comment by JarekToro** [comment] 2020-05-17 12:12
Getting same error. I am on version typescript 3.8.1

**Comment by bschlenk** [comment] 2020-05-20 11:57
Maybe it is because I am including [@types/node as a devDependency](https://github.com/bschlenk/node-roku-client/blob/6cf668d8235715d833aae9ec41698c4e95621592/package.json#L58). Do you have `@types/node` as a dependency/devDependency of your package? If installing `@types/node` fixes it for you, then I should move it to a regular dependency of this package.

**Comment by bschlenk** [comment] 2020-05-20 12:24
I'm not able to reproduce this. Can you provide some more info on repro steps?

Here's what I tried, using latest typescript (3.9.3):

```ts
// src/index.ts
import { Client } from 'roku-client';

async function main() {
  const client = new Client('abc');
  const res = await client.icon(123);
  const blob = await res.response.blob();
}
```

```json
// tsconfig.json
{
  "compilerOptions": {
    "lib": [],
    "strict": true,
    "sourceMap": true,
    "declaration": true,
    "outDir": "./dist"
  },
  "include": ["src"]
}
```

Then ran:

```sh
./node_modules/.bin/tsc
```

@JarekToro typescript@3.8.1 was never officially released - can you try with the latest typescript?

**Comment by JarekToro** [comment] 2020-05-20 15:26
`Dom ` Was not included in the libs array in tsconfig of my project. Adding that fixed it.

**Comment by bschlenk** [comment] 2020-05-27 00:42
Closing since a workaround has been found.

**Closed by bschlenk** 2020-05-27 00:42 UTC
